yarnPath: ".yarn/releases/yarn-berry.cjs"
logFilters:
  - code: YN0061
    level: discard
    # YN0061 warning (deprecated) is accurate, but unfixable when using jest
  - code: YN0032
    level: discard
    # YN0032 warning (node-gyp) is unreliable because of this bug:
    # https://github.com/yarnpkg/yarn/issues/8052#issuecomment-735764698
  - code: YN0013
    level: discard
    # YN0013 (not found in cache) does not seem actionable
    # It's always the same packages that show up, so I don't know why they wouldn't be cached
    # Anyways, the point of yarn is to download packages, so this warning is unhelpful.
